### PR TITLE
with orthopgraphy and simplified concept handling

### PR DESCRIPTION
**Pull request by xrotwang**
Orthgraphy handling isn't as good as expected(?), though.

### CODE REVIEW

**Review by SimonGreenhill — APPROVED** [review]
Thanks! Looks nicer :)

**Review by LinguList — APPROVED** [review]
And they said: "what do you want us to call this unsystematic notation system you used to collect those languages?" And he answered: "I want you to call it IPA".

Just illustrates nicely why IPA does not exist...

**Comment by SimonGreenhill** [comment]
Will merge and fix that test.

**Comment by SimonGreenhill** [comment]
The first I in IPA often seems to stand for "Idiosyncratic" :)

**Pull request merged**
